
version: "3.9"
services:
  myapp:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8080"
    ports:
      - "8000:8080"