# Generated by Django 5.0.3 on 2024-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_product_options_order_color_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_photos/'),
        ),
    ]
