# Generated by Django 5.0.3 on 2024-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
